import { documents } from '../lib/documents';
import { DocumentCard } from '../components/document-card';

export default function Home() {
  return (
    <section className="space-y-10">
      <div className="max-w-3xl space-y-4">
        <p className="text-sm uppercase tracking-wide text-primary-400">Documentation Portal</p>
        <h2 className="font-display text-2xl font-semibold text-slate-50 sm:text-3xl">
          Single destination for LVHN jumper server collaboration
        </h2>
        <p className="text-sm text-slate-400">
          Access the latest documentation, proposal materials, runbooks, and operational questionnaires required to
          enable Ionic Health to deliver eKVM updates via the LVHN-managed jumper server. PDFs are generated by the CI
          workflow and kept in sync with the markdown sources in this repository.
        </p>
      </div>
      <div className="grid gap-6 md:grid-cols-2">
        {documents.map((doc) => (
          <DocumentCard key={doc.id} doc={doc} />
        ))}
      </div>
    </section>
  );
}
