import Link from 'next/link';
import { documents } from '../lib/documents';
import { DocumentCard } from '../components/document-card';

export default function Home() {
  return (
    <section className="space-y-10">
      <div className="max-w-3xl space-y-4">
        <p className="text-sm uppercase tracking-wide text-primary-400">Documentation Portal</p>
        <h2 className="font-display text-2xl font-semibold text-slate-50 sm:text-3xl">
          Single destination for LVHN jumper server collaboration
        </h2>
        <p className="text-sm text-slate-400">
          Access the latest documentation, proposal materials, runbooks, and operational questionnaires required to
          enable Ionic Health to deliver eKVM updates via the LVHN-managed jumper server. PDFs are generated by the CI
          workflow and kept in sync with the markdown sources in this repository.
        </p>
        <div className="flex flex-wrap gap-3 pt-2">
          <Link
            className="inline-flex items-center gap-2 rounded-full border border-primary-500 bg-primary-500/10 px-5 py-2 text-sm font-medium text-primary-300 transition hover:bg-primary-500/20"
            href="/questionnaire"
          >
            Fill the Jumper Server Readiness Form
          </Link>
          <a
            className="inline-flex items-center gap-2 rounded-full border border-slate-700 px-4 py-2 text-sm text-slate-200 transition hover:border-primary-500 hover:text-primary-400"
            href="https://github.com/resper1965/jumpserver/blob/main/docs/proposal/LVHN-Infrastructure-Questionnaire.md"
            target="_blank"
            rel="noreferrer noopener"
          >
            View Markdown Version
          </a>
        </div>
      </div>
      <div className="grid gap-6 md:grid-cols-2">
        {documents.map((doc) => (
          <DocumentCard key={doc.id} doc={doc} />
        ))}
      </div>
    </section>
  );
}
