import Link from 'next/link';
import { documents } from '../lib/documents';
import { DocumentCard } from '../components/document-card';
import { ModeToggle } from '@/components/mode-toggle';
import { FileText, Github } from 'lucide-react';
import { Button } from '@/components/button';

export default function Home() {
  return (
    <div className="min-h-screen">
      {/* Header */}
      <header className="border-b">
        <div className="container mx-auto flex items-center justify-between py-4 px-6">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-lg bg-primary text-primary-foreground flex items-center justify-center font-bold">
              IH
            </div>
            <div>
              <h1 className="text-xl font-bold">Ionic Health</h1>
              <p className="text-xs text-muted-foreground">LVHN Documentation Portal</p>
            </div>
          </div>
          <div className="flex gap-2 items-center">
            <ModeToggle />
            <Button onClick={() => window.open('https://github.com/resper1965/jumpserver', '_blank')}>
              <Github className="h-[1.2rem] w-[1.2rem]" />
            </Button>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="container mx-auto px-6 py-16 space-y-8">
        <div className="max-w-3xl space-y-4">
          <div className="inline-flex items-center gap-2 rounded-full border px-4 py-1.5 text-sm">
            <FileText className="h-4 w-4" />
            <span>Documentation Portal</span>
          </div>
          <h2 className="text-4xl font-bold tracking-tight sm:text-5xl">
            LVHN eKVM Remote Update Documentation
          </h2>
          <p className="text-lg text-muted-foreground">
            Access the latest documentation, proposal materials, runbooks, and operational questionnaires required to
            enable Ionic Health to deliver eKVM updates via the LVHN-managed jumper server.
          </p>
          <div className="flex flex-wrap gap-3 pt-4">
            <Link href="/docs">
              <Button variant="primary" size="lg">
                Browse Documentation
              </Button>
            </Link>
            <Link href="/questionnaire">
              <Button variant="outline" size="lg">
                Fill Readiness Form
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* Documents Grid */}
      <section className="container mx-auto px-6 py-12">
        <div className="mb-8">
          <h3 className="text-2xl font-bold mb-2">Available Documents</h3>
          <p className="text-muted-foreground">
            PDFs are generated by the CI workflow and kept in sync with the markdown sources in this repository.
          </p>
        </div>
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {documents.map((doc) => (
            <DocumentCard key={doc.id} doc={doc} />
          ))}
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t mt-16">
        <div className="container mx-auto px-6 py-8">
          <div className="flex flex-col md:flex-row justify-between items-center gap-4">
            <div className="text-sm text-muted-foreground">
              <p>© 2025 Ionic Health — Documentation portal generated from markdown sources.</p>
              <p>Contact the project team for access support.</p>
            </div>
            <div className="flex gap-4">
              <a href="https://github.com/resper1965/jumpserver" target="_blank" rel="noopener noreferrer" className="text-sm text-muted-foreground hover:text-foreground">
                GitHub
              </a>
              <a href="mailto:raraujo@ionic.health" className="text-sm text-muted-foreground hover:text-foreground">
                Contact
              </a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
